model_list: 
  - model_name: claude-3-opus-20240229 
    litellm_params: 
      model: claude-3-opus-20240229
  - model_name: claude-3-sonnet-20240229 
    litellm_params: 
      model: claude-3-sonnet-20240229
  - model_name: claude-3-haiku-20240307 
    litellm_params: 
      model: claude-3-haiku-20240307